---

- name: activate changes
  checkmk_changes:
    url: "{{ cmk_site_url }}"
    user: "{{ cmk_site_user }}"
    password: "{{ cmk_site_password }}"
    allow_foreign_changes: yes
    comments: 'Changes made by Ansible'
    validate_certs: "{{ cmk_validate_certs }}"
  delegate_to: localhost
