---
- hosts: g_cmk_hosts
  gather_facts: smart
  tags: [all, agent]
  roles:
      - cmk_host_agent

- hosts: g_cmk_hosts
  gather_facts: smart
  tags: [all, plugins]
  roles:
      - cmk_host_plugins

- hosts: g_cmk_hosts
  gather_facts: smart
  tags: [all, register]
  roles:
      - cmk_host_registration
