---

- name: Install {{ needed_plugin }}
  get_url:
    url: "{{ cmk_site_url }}/check_mk/agents/plugins/{{ needed_plugin }}"
    dest: "{{ plugins_path }}/{{ needed_plugin }}"
    owner: root
    group: root
    mode: 0500  # Prevent users from editing this script on the host

- name: Install config file for {{ needed_plugin }}
  copy:
    src: "{{ cmk_plugin_base[ needed_plugin ].cfg }}"
    dest: "{{ config_path }}/{{ cmk_plugin_base[ needed_plugin ].cfg }}"
    owner: root
    group: root
    mode: 0400  # Prevent users from editing this file on the host
  when: cmk_plugin_base[ needed_plugin ].cfg is defined
