---

- name: Get process needed for {{ plugin_name.key }}
  win_shell: "(Get-Process | Where-Object {$_.ProcessName -like '*{{ plugin_name.value.cmd }}*'} | Get-Unique | Select-Object ProcessName | Format-Table -HideTableHeaders | Out-String).trim()"  # noqa yaml
  register: get_process
  failed_when: get_process.rc == 1
  changed_when: false
  when: by_process and plugin_name.value.cmd is defined

- name: Get file needed for {{ plugin_name.key }}
  win_stat:
    path: "{{ plugin_name.value.path }}"
  register: get_file
  changed_when: false
  when: by_files and plugin_name.value.path is defined

- name: Add {{ plugin_name.key }} to needed plugins
  set_fact:
    CMK_PLUGINS: "{{ CMK_PLUGINS + [ plugin_name.key ] }}"
  when: (get_process.stdout is defined and get_process.stdout_lines[0] | length > 0 ) or
        (get_file.stat is defined and get_file.stat.exists) or
        (by_package and plugin_name.value.pkg is defined and plugin_name.value.pkg in packages) or
        (plugin_name.value.force is defined and plugin_name.value.force)
