---
# Install Check_MK Agent on RedHat/CentOS/Fedora

- name: Download agent -> {{ cmk_agent.url.rpm }}
  get_url:
    url: "{{ cmk_agent.url.rpm }}"
    dest: "{{ cmk_host_linux_tmp }}"

- name: Install agent -> {{ cmk_agent.file.rpm }}
  become: yes
  yum:
      name: "{{ cmk_agent.file.rpm }}"
      state: present
      disable_gpg_check: yes
