---
# Install Check_MK Agent on Windows

- name: Get current agent version
  win_shell: |
      $cmk = "C:\Program Files (x86)\check_mk\check_mk_agent.exe"
      If (Test-Path $cmk) {
          (Get-Item $cmk).VersionInfo.ProductVersion
          } Else {
          "No agent installed"}
  register: cmk_agent_version
  changed_when: cmk_agent_version.stdout_lines[0] != cmk_version

- name: Download agent -> {{ cmk_agent.url.win }}
  # noqa no-handler
  win_get_url:
    url: "{{ cmk_agent.url.win }}"
    dest: "{{ cmk_host_windows_tmp }}"
  when: cmk_agent_version.changed

- name: Install agent -> {{ cmk_agent.file.win }}
  # noqa no-handler
  win_package:
    path: "{{ cmk_agent.file.win }}"
    state: present
    wait: true
  when: cmk_agent_version.changed

- name: Install agent config
  win_copy:
    src: "check_mk.ini"
    dest: "{{ cmk_agent.file.win_conf }}"
